### ISSUE TITLE
Which language can be supported?

### ISSUE THREAD

**Issue by perfecten** [kn4rfy/react-native-speech-notification#4]
thanks for your great component.

Which language can be supported?
en-US is OK.
is zh-CN NG?

thanks

**Comment by kn4rfy** [comment]
Yes it is supported. you can try using this code:
`SpeechNotification.speak({
  message: 'Hello',
  language: 'zh-CN'
});`

**Comment by iamaluckyman** [comment]
@kn4rfy Thank you very much. following your comment, Now my app has spoken chinese . Yeah!

Another question,
How can I check if a mobile phone has installed the TTS ?

**Comment by kn4rfy** [comment]
@pengfeiyan is it for ios or android?

**Comment by iamaluckyman** [comment]
@kn4rfy 
My app is for ios and android.
Maybe IOS7  has installed the TextToSpeech.
some androids need to install the TTS to speech.

so, I need to check , 
if  the TTS has  not been installed , the app will give some message, advices users to install the TTS .
