### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by amirmatin** [kn4rfy/react-native-speech-notification#5]
Hi, I have just installed the package but I am getting the following error : 

> Task :react-native-speech-notification:compileDebugJavaWithJavac
my-project\node_modules\react-native-speech-notification\android\src\main\java\co\ulimit\speechnotification\RCTSpeechNotification.java:30: error: method does not override or implement a method from a supertype
  @Override
  ^
1 error

thanks for your help in advance..

**Comment by kn4rfy** [comment]
Updating this module to work this latest version of react-native

**Comment by kn4rfy** [comment]
This issue is now fixed
